### ISSUE TITLE
On some android devices 'force' is being returned as 1 only in change method.

### ISSUE THREAD

**Issue by quizzy** [stuyam/pressure#67]
On some android devices, the force parameter for the change method always returns as 1 and 1 only - has this happened to anyone else? (devices tested were Sony Xperia Android 6.0.1 and a Samsung device). I also tried testing on a Wileyfox Swift 2 - android - chrome, which doesn't seem to have triggered at all. 

I'm unable to get direct access to these devices right now, but if you need more information from me let me know and I'll try and get a hold of them with the specs etc.

Thanks @stuyam.
______________
**Please provide information about the device you are seeing the issue on**
Device is a Sony Xperia
Operating system is  Android 6.0.1
Browser is Chrome

**Comment by stuyam** [comment]
Added some related references where similar conversations have been had before but not yet resolved. Thanks for posting this issue. 😄

**Comment by dalisoft** [comment]
This issue should be resolved. When use 3D touch in Android Chrome works, but target all changing from 0 to 1 in just less than 1sec. Polyfill time also not works

**Comment by dalisoft** [comment]
I have real access devicd. Or you can use Browserstack. I am use service as free. Free for open source projects as Pressurejs is free and open source

**Comment by stuyam** [comment]
I will have to check with Browserstack, I have access to it. However last I checked there wasn't an option to adjust the force applied to the a screen through Browserstack.

**Comment by dalisoft** [comment]
Pressurejs works best on real 3D touch supported device. I recommend Browserstack for android testing

**Comment by stuyam** [comment]
It's been too long but Im circling back and going to get this fixed. Was able to reproduce.

**Comment by dalisoft** [comment]
I there to test

**Comment by dalisoft** [comment]
I need this plug-in, but i need cross-device support, even in Chrome

**Comment by stuyam** [comment]
This is fixed in the latest release v2.1.2 https://github.com/stuyam/pressure/releases/tag/v2.1.2
Give it a try 👍

**Comment by sbormann** [comment]
I'm sorry, but it is still not working for some android-devices. Just tested it on Galaxy S7 via Browserstack and "All" and "Pointer event" jumps directly from zero to 1.

**Comment by dalisoft** [comment]
@sbormann look at forceify.js.org
